site_name: "serqlane"
site_description: "The serqlane programming language"
repo_url: https://github.com/serqlane/serqlane

use_directory_urls: false

# Theme
theme:
  name: material
  icon:
      logo: material/book-open-page-variant
      repo: fontawesome/brands/github
  features:
      - content.tabs.link
      - content.code.copy
      - search.suggest
      - search.highlight
  palette:
      - media: "(prefers-color-scheme: light)"
        scheme: default
        toggle:
            icon: material/weather-night
            name: Switch to dark mode
        primary: blue
        accent: blue
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        toggle:
            icon: material/weather-sunny
            name: Switch to light mode
        primary: blue
        accent: blue

nav:
  - Overview: index.md
  - Introduction: introduction.md
  - Language Reference: language-reference.md

markdown_extensions:
  - markdown.extensions.codehilite
  - pymdownx.escapeall
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  
